"""Tests for the Agent Script (.agent) input path.

The point of this path: the action's invocation target is IN the file
(`target: "apex://GetHealthRecordSummary"`), so the tool no longer resolves a
custom GenAiFunction to its Apex class through a Tooling API lookup. These tests
prove the bind happens with NO org call at all.

The fixture is a REAL authoring bundle generated by
`sf agent generate authoring-bundle` and compiled by Salesforce's own validator
(`sf agent validate` -> success), so the grammar under test is the vendor's.

Skips cleanly if node / @sf-agentscript/parser is not installed.

Run from the repo root:  python blast_radius/test_agentscript_loader.py
"""

import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import agentscript_loader as asl  # noqa: E402
from agent_analyzer import parse_agent_config  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.join(
    HERE, "..", "force-app", "main", "default", "aiAuthoringBundles",
    "HealthRecord_Assistant_AS", "HealthRecord_Assistant_AS.agent")

HAVE = asl.agentscript_available() and os.path.exists(BUNDLE)


class PureMappingTest(unittest.TestCase):
    """to_analyzer_config is pure - no org, no node needed."""

    IR = {
        "agent_name": "A",
        "topics": [{
            "name": "t",
            "actions": [
                {"local_name": "get_rec", "scheme": "apex",
                 "target_name": "GetHealthRecordSummary", "target": "apex://GetHealthRecordSummary"},
                {"local_name": "run_flow", "scheme": "flow",
                 "target_name": "BlastR_System_Flow", "target": "flow://BlastR_System_Flow"},
                {"local_name": "std", "scheme": "standardInvocableAction",
                 "target_name": "SomethingOpaque", "target": "standardInvocableAction://SomethingOpaque"},
            ],
        }],
    }

    def test_apex_and_flow_are_source_analysable(self):
        cfg = asl.to_analyzer_config(self.IR, running_user="u")
        kinds = {a["name"]: a["invocationTargetType"] for a in cfg["topics"][0]["actions"]}
        self.assertEqual(kinds["get_rec"], "apex")
        self.assertEqual(kinds["run_flow"], "flow")

    def test_unknown_scheme_is_opaque_not_clean(self):
        # standardInvocableAction:// / externalService:// etc. cannot be read from
        # source -> 'standard' -> PS507 honest-unknown, never a silent clean.
        cfg = asl.to_analyzer_config(self.IR, running_user="u")
        kinds = {a["name"]: a["invocationTargetType"] for a in cfg["topics"][0]["actions"]}
        self.assertEqual(kinds["std"], "standard")

    def test_config_parses_into_agent(self):
        agent = parse_agent_config(asl.to_analyzer_config(self.IR, running_user="u"))
        self.assertEqual(agent.name, "A")
        self.assertEqual(len(agent.actions), 3)


@unittest.skipUnless(HAVE, "node / @sf-agentscript/parser / bundle not available")
class RealBundleTest(unittest.TestCase):
    """Against the REAL .agent that Salesforce's own compiler validated."""

    @classmethod
    def setUpClass(cls):
        cls.ir = asl.extract(BUNDLE)

    def test_agent_name_from_config_block(self):
        self.assertEqual(self.ir["agent_name"], "HealthRecord_Assistant_AS")

    def test_apex_target_resolved_from_the_file_with_a_line(self):
        # THE POINT: no Tooling API, no org call - the class name is in the file.
        targets = asl.reached_targets(self.ir)
        apex = [t for t in targets if t[0] == "apex"]
        self.assertTrue(apex, "no apex:// target found")
        scheme, name, line = apex[0]
        self.assertEqual(name, "GetHealthRecordSummary")
        self.assertIsInstance(line, int)          # anchorable for an editor diagnostic

    def test_linked_and_mutable_variables_are_read(self):
        by_name = {v["name"]: v for v in self.ir["variables"]}
        self.assertEqual(by_name["EndUserId"]["modifier"], "linked")
        self.assertEqual(by_name["EndUserId"]["source"], "@MessagingSession.MessagingEndUserId")
        self.assertEqual(by_name["VerifiedCustomerId"]["modifier"], "mutable")

    def test_prompt_interpolations_are_located(self):
        # `{! @variables.x }` is a first-class AST node -> the data->prompt hop
        # that PS52x will build on.
        interps = [i for t in self.ir["topics"] for i in t["interpolations"]]
        self.assertTrue(interps)
        self.assertTrue(all(isinstance(i["line"], int) for i in interps))

    def test_end_to_end_config_binds_to_the_apex_action(self):
        cfg = asl.to_analyzer_config(self.ir, running_user="(permission set: HR_Agent_Minimal)")
        agent = parse_agent_config(cfg)
        apex = [a for a in agent.actions if a.target_type == "apex"]
        self.assertEqual([a.target for a in apex], ["GetHealthRecordSummary"])


if __name__ == "__main__":
    unittest.main(verbosity=2)
